### PR TITLE
Interpreter: Kill forked JVM whenever source files are changed

### LINKED ISSUE #558: Add restarting mode to `bloop run --watch`
Currently, `bloop run --watch` only works for self-terminating apps so that it's not applicable for non-terminating apps such as servers.

What about adding an option to kill the forked vm and restart it when a source file change is detected? This feature would be drop-in replacement of https://github.com/spray/sbt-revolver.

### PR DESCRIPTION
**Pull request by tindzk**
Start the JVM process asynchronously within `watch()` without waiting for its termination.

**To do:**
- [x] When Ctrl-C is pressed, kill the JVM process.
- [ ] Introduce a flag `--no-restart` to disable killing and restarting of the JVM process altogether. This would be useful if the JVM picks up changes on the class path, for example in combination with DCEVM.
- [ ] When there is already an active compilation run, either wait for its termination or interrupt it. Could you provide any pointers, @jvican?

Closes #558.

### CODE REVIEW

**Comment by jvican** [comment]
@tindzk There are some things I'd like to fix in master before fixing this, so if you don't mind I'm going to close the pull request and will reopen when they are fixed and then give you pointers on how to solve the remaining problems :smile:

**Comment by tindzk** [comment]
@jvican Did you already make those changes on `master`?

**Comment by jvican** [comment]
Not yet, but I'll ping you as soon as I have them ready :+1:

**Comment by Krever** [comment]
@jvican any update here maybe? :)

**Comment by jvican** [comment]
This can be implemented again @tindzk. If you or someone else is interested, please ping me, I'd be happy to give some pointers on how to implement this and tackle the todo list items.

**Comment by tindzk** [comment]
Excellent. I am taking a break of a few months at the moment. I can tackle it afterwards if it has not been resolved during that time.

**Comment by jvican** [comment]
Sounds good @tindzk, enjoy your break!

**Pull request closed without merging**
