### PR TITLE
Experiment with benchmarks

### PR DESCRIPTION
**Pull request by jvican**

### CODE REVIEW

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.weNsMtNXC5/2018-08-12-010910-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.0VpTrriWaI/2018-08-12-213228-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.sHnNgdw75E/2018-08-12-213715-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.Sl0RTnKOW6/2018-08-12-225507-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.5s6moMrhgW/2018-08-12-230040-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.3Nh6MlRV7I/2018-08-12-234247-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.2z38hSLmqF/2018-08-12-235617-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.RAJZrC33Ey/2018-08-13-011441-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Pull request merged**
