### PR TITLE
Publish website on merge

### PR DESCRIPTION
**Pull request by Duhemm**

### CODE REVIEW

**Comment by jvican** [comment]
Can you look into why the CI fails?

**Comment by Duhemm** [comment]
It fails because hugo is not installed in the CI. We need to upgrade the docker image.

**Comment by Duhemm** [comment]
Yay, it works, we just need to publish the real docker image (I've tried here with the image published under my name)

**Comment by Duhemm** [comment]
This should be ready for review @jvican :)

**Comment by jvican** [comment]
Feel free to merge when CI passes in last commit.

**Pull request merged**
