### PR TITLE
Upgrade directories version to match coursier's

### LINKED ISSUE #463: NoSuchMethodError running `bloop about`
Hi.

On my Linux box, I installed bloop using `curl -L https://github.com/scalacenter/bloop/releases/download/v1.0.0-M9/install.py | python`

I have started the server with `~/.bloop/bloop server` in an xterm.

Trying to run `bloop about` results in an exception:

```
~/.bloop/bloop about
May 02, 2018 3:59:22 PM com.martiansoftware.nailgun.NGSession run
INFO: Server unexpectedly exited with unhandled exception
java.lang.NoSuchMethodError: io.github.soc.directories.ProjectDirectories.fromProjectName(Ljava/lang/String;)Lio/github/soc/directories/ProjectDirectories;
	at bloop.io.Paths$.<init>(Paths.scala:19)
	at bloop.io.Paths$.<clinit>(Paths.scala)
	at bloop.Project$.loadAllFiles(Project.scala:44)
	at bloop.Project$.$anonfun$lazyLoadFromDir$1(Project.scala:56)
	at bloop.io.Timer$.timed(Timer.scala:9)
	at bloop.Project$.lazyLoadFromDir(Project.scala:54)
	at bloop.engine.State$.$anonfun$loadActiveStateFor$1(State.scala:118)
	at bloop.engine.State$.$anonfun$loadActiveStateFor$1$adapted(State.scala:117)
	at bloop.engine.caches.StateCache.computeAndSave$1(StateCache.scala:44)
	at bloop.engine.caches.StateCache.addIfMissing(StateCache.scala:54)
	at bloop.engine.State$.loadActiveStateFor(State.scala:117)
	at bloop.Cli$.run(Cli.scala:225)
	at bloop.Cli$.nailMain(Cli.scala:52)
	at bloop.Cli.nailMain(Cli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:345)

java.lang.NoSuchMethodError: io.github.soc.directories.ProjectDirectories.fromProjectName(Ljava/lang/String;)Lio/github/soc/directories/ProjectDirectories;
	at bloop.io.Paths$.<init>(Paths.scala:19)
	at bloop.io.Paths$.<clinit>(Paths.scala)
	at bloop.Project$.loadAllFiles(Project.scala:44)
	at bloop.Project$.$anonfun$lazyLoadFromDir$1(Project.scala:56)
	at bloop.io.Timer$.timed(Timer.scala:9)
	at bloop.Project$.lazyLoadFromDir(Project.scala:54)
	at bloop.engine.State$.$anonfun$loadActiveStateFor$1(State.scala:118)
	at bloop.engine.State$.$anonfun$loadActiveStateFor$1$adapted(State.scala:117)
	at bloop.engine.caches.StateCache.computeAndSave$1(StateCache.scala:44)
	at bloop.engine.caches.StateCache.addIfMissing(StateCache.scala:54)
	at bloop.engine.State$.loadActiveStateFor(State.scala:117)
	at bloop.Cli$.run(Cli.scala:225)
	at bloop.Cli$.nailMain(Cli.scala:52)
	at bloop.Cli.nailMain(Cli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:345)
```

Seems that this method has been removed from soc/directories-jvm in version 7, commit soc/directories-jvm@4305e70a93ab9acc6256b10f7f3087e9902d671f

Looking into the `blp-coursier` jar, there are class files in `io/github/soc/directories` which probably interfere with the files in `jars/directories-5.jar`.

### PR DESCRIPTION
**Pull request by jvican**
Fixes #463.

### CODE REVIEW

**Comment by avdv** [comment]
Hey, coursier switched to version 10 of directories in v1.1.0-M2, is there a reason you hold on to 7?

**Comment by jvican** [comment]
@tues Thanks for the review :wink:. :+1: on your suggestion to upgrade to 10, guys.
 
>  I don't know how important they are on those systems - probably it's just cosmetic so not worth changing now, I guess?
  
I didn't change it because it would modify the path of the bloop cache. That means that users in the systems affected (mainly osx and windows) will need to see how the compilation bridges are compiled again, and that may be annoying.
  
I don't own a Mac or Windows, are the qualifier and organisation important for a correct behaviour upon the creation of these directories?

**Comment by tues** [comment]
Not sure about Windows, but on Mac all it seems to do is prepending program name with dot-separated qualifier name and apparently not all Mac programs do that. Since I don't use Mac for development either I have asked a friend who is using both Bloop and Mac and he confirmed that everything is working fine and e.g. IntelliJ is even misusing the standard by creating `IntelliJIdea2018.1` directory so I guess it's better not to touch this if it works.

I guess this is worth a new release considering that installing Bloop using the official guide isn't working now?

P.S. I know you probably don't need reviews, but I hope they don't do any harm? :wink:

**Comment by jvican** [comment]
Thanks for confirming! Yeah, we'll try to release a new version soon. Need to write the release notes.

> P.S. I know you probably don't need reviews, but I hope they don't do any harm?

Absolutely not, feel free to submit your reviews :wink:

**Pull request merged**
