### PR TITLE
Fix clearing of screen in SourceWatcher + drone insanity fix

### PR DESCRIPTION
**Pull request by jvican**
For some reason, Drone doesn't seem to update the drone commit
message... Let's do it manually.

### CODE REVIEW

**Comment by jvican** [comment]
Don't merge yet.

**Comment by Duhemm** [comment]
Actually, I'm thinking that we should NOT clear the screen if the logs are verbose, otherwise we'll never see why the file watch got triggered.

**Comment by jvican** [comment]
Or, we can move the `debug` after we clear the screen.

**Comment by Duhemm** [comment]
That should work too, we can always change that if it's annoying

**Comment by jvican** [comment]
Let's merge this as soon as CI is green. I want a release out tonight :man_dancing:

**Pull request merged**
