### PR TITLE
chore: bump sbt version

### PR DESCRIPTION
**Pull request by kpodsiad**
Let's see what will fail

### CODE REVIEW

**Comment by kpodsiad** [comment]
```shell
[error] stack trace is suppressed; run last docs / update for the full output
[error] (docs / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error]         * com.thesamet.scalapb:scalapb-runtime_2.12:0.11.4 (early-semver) is selected over {0.8.0-RC1}
[error]             +- org.scalameta:common_2.12:4.4.32                   (depends on 0.11.4)
[error]             +- ch.epfl.scala:zinc-persist_2.12:1.3.0-M4+47-d881fa2f (depends on 0.8.0-RC1)
[error]             +- ch.epfl.scala:zinc-core_2.12:1.3.0-M4+47-d881fa2f  (depends on 0.8.0-RC1)
[error] 
[error] 
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
```
needs https://github.com/scalacenter/bloop/pull/1662

**Comment by kpodsiad** [comment]
Ok, test are more or less passing, I'll migrate `*.sbt` to use slash syntax now.

**Comment by kpodsiad** [comment]
CI is green, the last commit removes only old todo thus I marked it as `skip ci`

**Review by tgodzik — APPROVED** [review]
LGTM!

**Pull request merged**
