### PR TITLE
Unify implementation of normal and pipelined compilation

### PR DESCRIPTION
**Pull request by jvican**
Previously, we were using two different task scheduling implementations for
pipelined and normal compilation. Let's check what the overhead of only
using the pipelined task implementation is.

### CODE REVIEW

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.X4BsqItfC0/2018-09-11-143642-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please 073bcdf8ae79c99e125d7641a39350bf7ebf5aa3

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Pull request merged**
