### PR TITLE
Clear screen before each watch iteration

### PR DESCRIPTION
**Pull request by jvican**
From https://stackoverflow.com/questions/2979383/java-clear-the-console.

### CODE REVIEW

**Comment by jvican** [comment]
Fixes https://github.com/scalacenter/bloop/issues/330.

**Comment by Duhemm** [comment]
What about Windows?

**Comment by jvican** [comment]
Doesn't Windows support escape characters? I think it does. https://en.wikipedia.org/wiki/ANSI_escape_code I don't care about not supporting Windows versions < 10.

**Comment by Duhemm** [comment]
This comment hints that it doesn't work: https://stackoverflow.com/questions/2979383/java-clear-the-console#comment79501906_32295974

I don't think it matters that much. I hope for people on Windows they use a better terminal.

**Comment by jvican** [comment]
Let's try to deal with this misbehaviour in the future then.

**Comment by olafurpg** [comment]
I propose you don't clear the screen on Windows if you suspect it will cause problems. It's better to have somebody more knowledgeable about Windows contribute window clearing.

**Comment by jvican** [comment]
That makes total sense.

**Pull request merged**
