### PR TITLE
SBT exports empty runtime classpath

### PR DESCRIPTION
**Pull request by attilapiros**
I believe that case worth at least a debug log.

### CODE REVIEW

**Comment by attilapiros** [comment]
First of all thanks for this project this is extremely useful.  

I use it for spark development and my problem is the tests are nut running.

Example:
```
$ cat project/metals.sbt
// DO NOT EDIT! This file is auto-generated.
// This file enables sbt-bloop to create bloop config files.

addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.2-3-96600d5d")
```



```
$ vim .bloop/tags-test.json
{
    "version" : "1.4.0",
    "project" : {
        "name" : "tags-test",
        "directory" : "/Users/attilazsoltpiros/git/attilapiros/reviewing/common/tags",
        "workspaceDir" : "/Users/attilazsoltpiros/git/attilapiros/reviewing",
        "sources" : [
            "/Users/attilazsoltpiros/git/attilapiros/reviewing/common/tags/src/test/scala-2.12",
            "/Users/attilazsoltpiros/git/attilapiros/reviewing/common/tags/src/test/scala",
            "/Users/attilazsoltpiros/git/attilapiros/reviewing/common/tags/src/test/java",
            "/Users/attilazsoltpiros/git/attilapiros/reviewing/common/tags/target/scala-2.12/src_managed/test"
        ],
        "dependencies" : [
            "tags"
        ],
        "classpath" : [
            "/Users/attilazsoltpiros/git/attilapiros/reviewing/.bloop/tags/scala-2.12/classes",
            "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.10.jar",
            "/Users/attilazsoltpiros/.ivy2/cache/org.spark-project.spark/unused/jars/unused-1.0.0.jar",
            "/Users/attilazsoltpiros/.ivy2/cache/org.scalatest/scalatest_2.12/bundles/scalatest_2.12-3.0.8.jar",
            "/Users/attilazsoltpiros/.ivy2/cache/org.scalactic/scalactic_2.12/bundles/scalactic_2.12-3.0.8.jar",
            "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.10.jar",
            "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.2.0.jar",
            "/Users/attilazsoltpiros/.ivy2/cache/junit/junit/jars/junit-4.12.jar",
            "/Users/attilazsoltpiros/.ivy2/cache/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.3.jar",
            "/Users/attilazsoltpiros/.ivy2/cache/com.novocode/junit-interface/jars/junit-interface-0.11.jar",
            "/Users/attilazsoltpiros/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar"
        ],
        "out" : "/Users/attilazsoltpiros/git/attilapiros/reviewing/.bloop/tags",
        "classesDir" : "/Users/attilazsoltpiros/git/attilapiros/reviewing/.bloop/tags/scala-2.12/test-classes",
        "resources" : [
            "/Users/attilazsoltpiros/git/attilapiros/reviewing/common/tags/src/test/resources",
            "/Users/attilazsoltpiros/git/attilapiros/reviewing/common/tags/target/scala-2.12/resource_managed/test"
        ],
        "scala" : {
            "organization" : "org.scala-lang",
            "name" : "scala-compiler",
            "version" : "2.12.10",
            "options" : [
                "-unchecked",
                "-deprecation",
                "-feature",
                "-explaintypes",
                "-target:jvm-1.8",
                "-P:genjavadoc:out=/Users/attilazsoltpiros/git/attilapiros/reviewing/common/tags/target/java",
                "-P:genjavadoc:strictVisibility=true",
                "-Xplugin:/Users/attilazsoltpiros/.ivy2/cache/com.typesafe.genjavadoc/genjavadoc-plugin_2.12.10/jars/genjavadoc-plugin_2.12.10-0.16.jar",
                "-target:jvm-1.8",
                "-sourcepath",
                "/Users/attilazsoltpiros/git/attilapiros/reviewing"
            ],
            "jars" : [
                "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.10.jar",
                "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.12.10.jar",
                "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.10.jar",
                "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.0.6.jar",
                "/Users/attilazsoltpiros/.ivy2/cache/jline/jline/jars/jline-2.14.6.jar",
                "/Users/attilazsoltpiros/.ivy2/cache/org.fusesource.jansi/jansi/jars/jansi-1.12.jar"
            ],
            "setup" : {
                "order" : "mixed",
                "addLibraryToBootClasspath" : true,
                "addCompilerToClasspath" : false,
                "addExtraJarsToClasspath" : false,
                "manageBootClasspath" : true,
                "filterLibraryFromClasspath" : true
            }
        },
        "java" : {
            "options" : [
                "-encoding",
                "UTF-8",
                "-source",
                "1.8",
                "-target",
                "1.8",
                "-Xlint:unchecked"
            ]
        },
        "test" : {
            "frameworks" : [
                {
                    "names" : [
                        "org.scalacheck.ScalaCheckFramework"
                    ]
                },
                {
                    "names" : [
                        "org.specs2.runner.Specs2Framework",
                        "org.specs2.runner.SpecsFramework"
                    ]
                },
                {
                    "names" : [
                        "org.specs.runner.SpecsFramework"
                    ]
                },
                {
                    "names" : [
                        "org.scalatest.tools.Framework",
                        "org.scalatest.tools.ScalaTestFramework"
                    ]
                },
                {
                    "names" : [
                        "com.novocode.junit.JUnitFramework"
                    ]
                }
            ],
            "options" : {
                "excludes" : [
                ],
                "arguments" : [
                    {
                        "args" : [
                            "-v",
                            "-a"
                        ],
                        "framework" : {
                            "names" : [
                                "com.novocode.junit.JUnitFramework"
                            ]
                        }
                    },
                    {
                        "args" : [
                            "-oDF"
                        ]
                    },
                    {
                        "args" : [
                        ],
                        "framework" : {
                            "names" : [
                                "com.novocode.junit.JUnitFramework"
                            ]
                        }
                    },
                    {
                        "args" : [
                        ],
                        "framework" : {
                            "names" : [
                                "org.scalatest.tools.Framework",
                                "org.scalatest.tools.ScalaTestFramework"
                            ]
                        }
                    }
                ]
            }
        },
        "platform" : {
            "name" : "jvm",
            "config" : {
                "home" : "/Users/attilazsoltpiros/.sdkman/candidates/java/current",
                "options" : [
                    "-Duser.dir=/Users/attilazsoltpiros/git/attilapiros/reviewing/common/tags",
                    "-Xmx3g",
                    "-Djava.io.tmpdir=/Users/attilazsoltpiros/git/attilapiros/reviewing/target/tmp",
                    "-Dspark.test.home=/Users/attilazsoltpiros/git/attilapiros/reviewing",
                    "-Dspark.testing=1",
                    "-Dspark.port.maxRetries=100",
                    "-Dspark.master.rest.enabled=false",
                    "-Dspark.memory.debugFill=true",
                    "-Dspark.ui.enabled=false",
                    "-Dspark.ui.showConsoleProgress=false",
                    "-Dspark.unsafe.exceptionOnMemoryLeak=true",
                    "-Dsun.io.serialization.extendedDebugInfo=false",
                    "-Dderby.system.durability=test",
                    "-Dio.netty.tryReflectionSetAccessible=true",
                    "-ea",
                    "-Xmx4g",
                    "-Xss4m",
                    "-XX:+UseParallelGC",
                    "-XX:-UseDynamicNumberOfGCThreads"
                ]
            },
            "mainClass" : [
            ],
            "classpath" : [
            ],
            "resources" : [
            ]
        },
        "resolution" : {
            "modules" : [
                {
                    "organization" : "org.scala-lang",
                    "name" : "scala-library",
                    "version" : "2.12.10",
                    "artifacts" : [
                        {
                            "name" : "scala-library",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.10.jar"
                        },
                        {
                            "name" : "scala-library",
                            "classifier" : "sources",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.12.10-sources.jar"
                        }
                    ]
                },
                {
                    "organization" : "org.spark-project.spark",
                    "name" : "unused",
                    "version" : "1.0.0",
                    "artifacts" : [
                        {
                            "name" : "unused",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.spark-project.spark/unused/jars/unused-1.0.0.jar"
                        },
                        {
                            "name" : "unused",
                            "classifier" : "sources",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.spark-project.spark/unused/srcs/unused-1.0.0-sources.jar"
                        }
                    ]
                },
                {
                    "organization" : "org.scalatest",
                    "name" : "scalatest_2.12",
                    "version" : "3.0.8",
                    "artifacts" : [
                        {
                            "name" : "scalatest_2.12",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scalatest/scalatest_2.12/bundles/scalatest_2.12-3.0.8.jar"
                        },
                        {
                            "name" : "scalatest_2.12",
                            "classifier" : "sources",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scalatest/scalatest_2.12/srcs/scalatest_2.12-3.0.8-sources.jar"
                        }
                    ]
                },
                {
                    "organization" : "org.scalactic",
                    "name" : "scalactic_2.12",
                    "version" : "3.0.8",
                    "artifacts" : [
                        {
                            "name" : "scalactic_2.12",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scalactic/scalactic_2.12/bundles/scalactic_2.12-3.0.8.jar"
                        },
                        {
                            "name" : "scalactic_2.12",
                            "classifier" : "sources",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scalactic/scalactic_2.12/srcs/scalactic_2.12-3.0.8-sources.jar"
                        }
                    ]
                },
                {
                    "organization" : "org.scala-lang",
                    "name" : "scala-reflect",
                    "version" : "2.12.10",
                    "artifacts" : [
                        {
                            "name" : "scala-reflect",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.10.jar"
                        },
                        {
                            "name" : "scala-reflect",
                            "classifier" : "sources",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang/scala-reflect/srcs/scala-reflect-2.12.10-sources.jar"
                        }
                    ]
                },
                {
                    "organization" : "org.scala-lang.modules",
                    "name" : "scala-xml_2.12",
                    "version" : "1.2.0",
                    "artifacts" : [
                        {
                            "name" : "scala-xml_2.12",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.2.0.jar"
                        },
                        {
                            "name" : "scala-xml_2.12",
                            "classifier" : "sources",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/srcs/scala-xml_2.12-1.2.0-sources.jar"
                        }
                    ]
                },
                {
                    "organization" : "junit",
                    "name" : "junit",
                    "version" : "4.12",
                    "artifacts" : [
                        {
                            "name" : "junit",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/junit/junit/jars/junit-4.12.jar"
                        },
                        {
                            "name" : "junit",
                            "classifier" : "sources",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/junit/junit/srcs/junit-4.12-sources.jar"
                        }
                    ]
                },
                {
                    "organization" : "org.hamcrest",
                    "name" : "hamcrest-core",
                    "version" : "1.3",
                    "artifacts" : [
                        {
                            "name" : "hamcrest-core",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.3.jar"
                        },
                        {
                            "name" : "hamcrest-core",
                            "classifier" : "sources",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.hamcrest/hamcrest-core/srcs/hamcrest-core-1.3-sources.jar"
                        }
                    ]
                },
                {
                    "organization" : "com.novocode",
                    "name" : "junit-interface",
                    "version" : "0.11",
                    "artifacts" : [
                        {
                            "name" : "junit-interface",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/com.novocode/junit-interface/jars/junit-interface-0.11.jar"
                        },
                        {
                            "name" : "junit-interface",
                            "classifier" : "sources",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/com.novocode/junit-interface/srcs/junit-interface-0.11-sources.jar"
                        }
                    ]
                },
                {
                    "organization" : "org.scala-sbt",
                    "name" : "test-interface",
                    "version" : "1.0",
                    "artifacts" : [
                        {
                            "name" : "test-interface",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar"
                        },
                        {
                            "name" : "test-interface",
                            "classifier" : "sources",
                            "path" : "/Users/attilazsoltpiros/.ivy2/cache/org.scala-sbt/test-interface/srcs/test-interface-1.0-sources.jar"
                        }
                    ]
                }
            ]
        },
        "tags" : [
            "test"
        ]
    }
}
```

```
$ bloop test tags-test --verbose
...
[D] Skipping delete of /Users/attilazsoltpiros/git/attilapiros/reviewing/.bloop/tags/bloop-internal-classes/test-classes-bloop-cli-yt0a1YpDQ6a_aJLP71G34A== associated with no-op result
[D] Preparing test execution for tags-test
[D] Skipping test framework org.scalacheck.ScalaCheckFramework as the class not be found
[D] Skipping test framework org.specs2.runner.Specs2Framework as the class not be found
[D] Skipping test framework org.specs2.runner.SpecsFramework as the class not be found
[D] Skipping test framework org.specs.runner.SpecsFramework as the class not be found
[D] Skipping test framework org.scalatest.tools.Framework as the class not be found
[D] Skipping test framework org.scalatest.tools.ScalaTestFramework as the class not be found
[D] Skipping test framework com.novocode.junit.JUnitFramework as the class not be found
[E] Missing configured test frameworks in tags-test
===============================================
Total duration: 0ms
No test suites were run.
===============================================
[D] Test suites failed: false
[D] Elapsed: 43.761096 ms
```

**Comment by jvican** [comment]
Hey @attilapiros, thanks for submitting this PR. Before we discuss the debug log, in which test framework are your tests written? The expectation here is that bloop should find the class when the test jar is present in the classpath of the project.

**Comment by attilapiros** [comment]
hi @jvican!

So I am building the upstream Apache Spark: https://github.com/apache/spark/.

My first example might be not the best one as there are no test in the tags but I get the same for core-test:
```
[D] Skipping test framework org.scalacheck.ScalaCheckFramework as the class not be found
[D] Skipping test framework org.specs2.runner.Specs2Framework as the class not be found
[D] Skipping test framework org.specs2.runner.SpecsFramework as the class not be found
[D] Skipping test framework org.specs.runner.SpecsFramework as the class not be found
[D] Skipping test framework org.scalatest.tools.Framework as the class not be found
[D] Skipping test framework org.scalatest.tools.ScalaTestFramework as the class not be found
[D] Skipping test framework com.novocode.junit.JUnitFramework as the class not be found
[E] Missing configured test frameworks in core-test
===============================================
Total duration: 0ms
No test suites were run.
===============================================
[D] Test suites failed: false
[D] Elapsed: 98183.331533 ms
```

I believe it is mostly scalatest (but there are few junit here as well).

**Comment by attilapiros** [comment]
But resolution/modules contains the scalatest even for tags-test see the json above. Should not it be used? Is not the .bloop/*.json is the basis to resolve the jars?

**Comment by Arthurm1** [comment]
Your "Platform"{ "Classpath" } is specified but blank.  Don't the tests use that as it's the runtime classpath?  Try copying the compile classpath stuff into that section.  Or deleting the "Platform"{ "Classpath" }

**Comment by attilapiros** [comment]
It was generated by `sbt bloopInstall`. Are the people editing this json by hand???

**Comment by attilapiros** [comment]
@Arthurm1 you must be right regarding the route cause: after deleting the "platform"...:

```
[D] Test server established connection with remote JVM.
[D] Sent task defs to test server: List()
[D] Create a single-thread test executor
[D] Test server has been successfully closed.
[D] The process is closed. Emptying buffer...
[D] Forked process exited with code: 0
[D] Process 40536 exited with code: 0
===============================================
Total duration: 0ms
No test suites were run.
===============================================
[D] Test suites failed: false
[D] Elapsed: 534.983133 ms
```

**Comment by Arthurm1** [comment]
Ha - no.  But the runtime classpath is fairly new and it's quite possible not many have used it.  You can change your issue title to "SBT exports empty runtime classpath".  The classpath should either be populated or not specified at all.

**Comment by jvican** [comment]
No need to do that, as it’s expected sbt doesn’t export the runtime classpath, it’s not a supported feature because of sbt limitations. What’s not expected is that your use case doesn’t work, this is an important bug. I’ll look into this a little bit later

**Comment by attilapiros** [comment]
Anyway guys you are awesome! 
Thanks for looking into this!

**Pull request closed without merging**
