### PR TITLE
Use java 8 or newer on macOS

### PR DESCRIPTION
**Pull request by fredfp**
fix for https://github.com/scalacenter/bloop/issues/933

### CODE REVIEW

**Comment by jvican** [comment]
This PR is good but as I said in the linked ticket we should probably figure out a way we can do this without regressing on performance, as the default GC in versions bigger than 8 is significantly (around 20%) slower in previous experiments.
  
So, that would entail adding the full parallel GC options to the jvmopts file after the installation of bloop in Homebrew. I recommend you first read the bloop server reference guide in the bloop website and then looking at the `ReleaseUtils` source in bloop's project build to modify the HomeBrew installation recipe to add the necessary jvm options.

**Comment by fredfp** [comment]
Thanks for the explanation, I've quickly hacked a (naive) way of trying different versions at runtime. What are your thoughts about it? If you don't like it I'll try to have a look at the `ReleaseUtils` you mentioned

**Comment by lavrov** [comment]
While slower compilation on later versions of java is a bummer bloop is used by other tools such as metals etc. I think it make sense to relax requirements and allow 1.8+ with notice that 1.8 gives the best performance.

**Comment by jvican** [comment]
Sorry for my slow feedback, I'm still giving this more thought. I'll reach back whenever I've made up my mind what the best thing to do here is.

**Comment by jvican** [comment]
Hey @fredfp, in `1.4.0` we're going to be changing the way installation works in macOS. Instead of using the script with coursier and forcing the version, we will be relying on the default Java version in your system. The CLI now has the capability to start the server in the background, so whenever we do start the server we will try to figure out the environment and use the right JVM options.
  
I think we can close this pull request since this change will no longer be required in 1.4.0. Thanks a lot for starting this discussion and caring about opening a pull request.

**Pull request closed without merging**
