### PR TITLE
WIP/experiment: try to fix ci

### PR DESCRIPTION
**Pull request by jchyb**
No idea what is going on but I'll try some things and see how those pan out

### CODE REVIEW

**Comment by tgodzik** [comment]
Looks like I can't reproduce it on my linux either. I will try on another machine, but this is pretty weird.

**Comment by jchyb** [comment]
The partial revert of the related part of my commit didn't work so now I am trying to revert the whole thing and see if the issue really is there

**Comment by tgodzik** [comment]
Looks like it might be a coincidence that this happen around the same time as merging your PR then :thinking: 

Maybe it was ubuntu update?

**Comment by tgodzik** [comment]
Thanks @jchyb for checking this out! I managed to fix it separately

**Pull request closed without merging**
