### PR TITLE
Clean all projects by default

### LINKED ISSUE #593: Redefine the semantics of clean without arguments
If you run `bloop clean` without specifying a project, nothing happen and it return a 0 (success) return code. I would expect that either:

1)  bloop prints the same error message as for the `compile` or `test` sub command (that would be `Required project name not specified for 'clean'.`) and return the same return code
2)  it cleans all the projects. It's not uncommon for clean commands to clean basically everything.

I think that 1 would the more consistent and less surprising.  

Likely related to that issue, the help message for the `-p` argument of `bloop clean` is different that the one for the `compile` and `test` sub command (it doesn't specify that the remaining arguments are used). It's also not very clear from the help message that clean can work with multiple projects as arguments.

### PR DESCRIPTION
**Pull request by tues**
Also add `CleanTaskSpec`, fix documentation and remove some unused variables/parameters.

Closes #593.

### CODE REVIEW

**Comment by tues** [comment]
Yeah, I'm not sure what's wrong with that. I can clearly see `frontend/src/main/scala/bloop/Project.scala` file in the repo, there's a `final case class Project` inside, and it compiles and works fine on my machine. Also passed some of the CI builds. Really weird :thinking:

**Comment by jvican** [comment]
The issue is likely that you have not rebased on top of the latest master? I merged recently https://github.com/scalacenter/bloop/pull/653 which moves `Project` around.

**Comment by jvican** [comment]
Yes, the CI will only really build either the last commit of your PR or any future commit in an open PR. Previous commits are not run because they were submitted to the repo before a PR is open. We do this to save resources.

**Comment by tues** [comment]
I mean `windows extra` and `windows community-build` always succeed because they don't seem to do anything - I didn't notice it at first and thought that some builds failed and some passed, so it must be random failure.

Anyway, `windows basic` failed again, but this time it doesn't look like my fault :wink:

**Comment by jvican** [comment]
We're experiencing some spurious failures in the Windows CI lately. Feel free to restart the build if it happens again (I just did, looking forward to merging this).

**Comment by jvican** [comment]
Looks like I've fixed the root of our spurious CI failures, so they shouldn't happen again in the future :wink: I'll be merging this as soon as I've got green light.

**Comment by tues** [comment]
Thanks :slightly_smiling_face: I'm afraid I lack permissions to restart builds, though, unless you're talking about artificially amending some commit to trick CI into rebuilding automatically.

**Pull request merged**
