### PR TITLE
Import Gradle test system properties to test framework config

### PR DESCRIPTION
**Pull request by pkolaczk**
This allows for some limited configurability of most common test frameworks.

### CODE REVIEW

**Comment by pkolaczk** [comment]
Thank you so much!

**Comment by pkolaczk** [comment]
One more thing that would be a nice to have is also exporting the `jvmArgs` and environment for the forked test JVM. Gradle has these properties, but currently I had no place to copy them to. I would have to change the JSON format - is it ok to add new fields?

**Comment by jvican** [comment]
The story for supporting platform arguments for tests isn't clear at this moment and needs more thought before we decide that adding new fields to the JSON configuration file is okay.
  
The jvm args and environment for a test build target could be added to the platform field of the JSON configuration file in those cases where the test build targets are independent from the compile build targets. I think this is the case for gradle, so you could piggyback on serializing jvm args and home to the platform of the test build target and then modify bloop test internals to use the platform while running tests (if we don't already do, which I don't remember).

**Comment by pkolaczk** [comment]
Yes, that makes sense. I forgot we have a separate platform settings for the test build target :)

**Pull request merged**
