### PR TITLE
Improve gradle dependency detection

### LINKED ISSUE #1311: Undetected Gradle test dependencies are ignored
Given a Gradle project setup with subprojects:

- `a`
- `b`, which depends on `a.test` artefacts

The `b-test.json` bloop file generated from `bloopInstall` does not take the `a.test`dependency  into account (`a-test` not a dependency and its output dir is not on the classpath). This means `bloop test b` does not work, instead failing with 

```shell
❯ bloop test b
Compiling b-test (1 Scala source)
[E] [E4] b/src/test/scala/com/beachape/BSpec.scala:9:3
[E]      not found: value it
[E]      L9:   it("should lol") {
[E]            ^
[E] [E3] b/src/test/scala/com/beachape/BSpec.scala:6:12
[E]      not found: value yo
[E]      L6:     assert(yo == "yo")
[E]                     ^
[E] [E2] b/src/test/scala/com/beachape/BSpec.scala:5:3
[E]      not found: value it
[E]      L5:   it("should yo") {
[E]            ^
[E] [E1] b/src/test/scala/com/beachape/BSpec.scala:3:21
[E]      not found: type ASpecLike
[E]      L3: class BSpec extends ASpecLike {
[E]                              ^
[E] b/src/test/scala/com/beachape/BSpec.scala: L3 [E1], L5 [E2], L6 [E3], L9 [E4]
Compiled b-test (45ms)
[E] Failed to compile 'b-test'
```

I've put up a basic repro here with more details in the README https://github.com/lloydmeta/bloop-gradle-subprojects

I've looked at https://github.com/scalacenter/bloop/issues/800, https://github.com/scalacenter/bloop/issues/808, and https://github.com/scalacenter/bloop/issues/818, which seem to handle this, but it seems to be broken.

### LINKED ISSUE #1312: Gradle plugin doesn't handle `scalaCompilerPlugins`
When you use `scalaCompilerPlugins` to add a scalac plugin as per [the docs](https://docs.gradle.org/current/userguide/scala_plugin.html#sec:scala_compiler_plugins), it doesn't appear to work or get picked up by the bloop definition from `bloopInstall`.

For instance, I have a project where I have `-Xfatal-warnings` enabled and added the [`silencer`](https://github.com/ghik/silencer) plugin to selectively silence deprecation errors. While it works in Gradle, the generated bloop project errors out despite adding `silent` annotations.

Example min repro project: https://github.com/lloydmeta/bloop-with-gradle-and-silencer

### PR DESCRIPTION
**Pull request by Arthurm1**
Project dependency discovery and classpath creation reworked to handle classpath ordering issues and project sourceset identification issues.

Add [TestFixtures](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures) functionality.
Add [ScalaCompilerPlugins](https://docs.gradle.org/current/userguide/scala_plugin.html#sec:scala_compiler_plugins) functionality. Fixes #1312
Cope with lazily defined archives. Fixes #1311
Remove irrelevant artifacts populating resolution modules
Bump max version compatibility to Gradle 6.5

### CODE REVIEW

**Comment by Arthurm1** [comment]
Spurious test failure (I assume): timeout in TcpBspProtocolSpec on Graal Windows

**Comment by jvican** [comment]
As I said, I'm merging, feel free to answer those questions whenever you have some time @Arthurm1 :smile:

**Comment by Arthurm1** [comment]
I see what you mean - all projects are resolved every time a single project is resolved - I'm unsure if Gradle itself caches this - I'll look into it.

I'll also have a look an making project dependencies non-transitive again - I didn't think this would matter and it was easier for me :-)

The only thing to improve the integration that springs to mind at the moment is to add `--parallel` to the call Metals makes to `gradlew bloopInstall`.  This speeds up the install in multi-module exports that don't have `org.gradle.parallel=true` in their `gradle.properties`
In my 130 module/buildTarget project it goes from 11 seconds down to 4 seconds.
I was going to have a look at how easy #1201 is to implement but my Android knowledge is thin.
Otherwise I think the Gradle export is fairly comprehensive now.  Do you know of any projects on GitHub that don't export correctly?  I can have a look at them.

**Comment by jvican** [comment]
> Otherwise I think the Gradle export is fairly comprehensive now. Do you know of any projects on GitHub that don't export correctly? I can have a look at them.
  
I do not know of more gradle projects that don't work well with Bloop. So far my gradle builds at work are working fine, module the performance annoyance of gradle not caching resolution.

> I see what you mean - all projects are resolved every time a single project is resolved - I'm unsure if Gradle itself caches this - I'll look into it.
  
Great! This would be a super important life-of-quality improvement.
  
> The only thing to improve the integration that springs to mind at the moment is to add --parallel to the call Metals makes to `gradlew bloopInstall`. This speeds up the install in multi-module exports that don't have org.gradle.parallel=true in their gradle.properties
  
Awesome, I didn't know about this, it's good to know, thanks :smile:
  
One thing I've been thinking: imagine gradle-bloop would take over gradle Scala integration. How could we implement cross-building projects in a nice way? Is there some state of the art here? I would like to have the opportunity to define cross-built Scala projects (for other platforms as well) so that we can use gradle to do what's possible in other builds. Do you have any thoughts here?

**Pull request merged**
