### PR TITLE
Rebase zinc and redesign build pipelining

### PR DESCRIPTION
**Pull request by jvican**
Information on the commit messages. The build pipelining redesign has
been done to minimize the diff with upstream zinc and to improve even
more performance. There is one incremental compiler error caught by our
test suite that I'm investigating, but in the meanwhile I submit this
pull request and kickstart the benchmarks.

Fixes https://github.com/scalacenter/bloop/issues/806
Fixes https://github.com/scalacenter/bloop/issues/817 (most likely)

Unblocks https://github.com/scalacenter/bloop/issues/588

### CODE REVIEW

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by jvican** [comment]
test performance please

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by jvican** [comment]
test performance plesae

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Pull request merged**
