### PR TITLE
Offload compilation from sbt to Bloop

### PR DESCRIPTION
**Pull request by jvican**
Fixes https://github.com/scalacenter/bloop/issues/315

### CODE REVIEW

**Comment by jvican** [comment]
CI is passing. I'm going to merge this PR because all the documentation and the gifs will be in a follow-up PR. I want to start rebasing every change in the PR pipeline onto this one, too, which seems to fix some spurious errors we were experiencing in master. This PR doesn't include scripted tests for offloading compilation and there are still some missing docs which will be done in a follow-up PR.

**Comment by kubukoz** [comment]
Super excited about this!

**Comment by kluen** [comment]
@jvican Hi, I'm also very excited about this. How exactly can offloading be enabled? I wasn't able to find anything in the Bloop documentation, only [this concept](https://scalacenter.github.io/bloop/docs/offloading-compilation-sbt#offloading-compilation-from-sbt).
If this is not ready yet, are there any follow-up issues I could subscribe to?

**Comment by tgodzik** [comment]
@kluen unfortunately it never got out of being experimental and there are not current plans to work on it further. Jorge is no longer working in the Scala Center, so it's doubtful he will have time to continue working on this.

I would love to take a look, but unfortunately there are much more pressing issues currently I need to deal with. If there is a broader community interest it would be possible to raise it as a proposal to the Scala Center advisory board through the community representatives.

**Comment by igor-ramazanov** [comment]
The idea sounds really good, because it'll allow to waste much less resources.

I often use bloop for the local development and import projects into the IntelliJ IDEA as a BSP projects, so I use the same bloop process across multiple projects keeping it hot.

However, sometimes I need to run various sbt related tasks, like building Docker containers and I **have to** run another sbt process for that, basically, duplicating the work which could be avoided.

**Comment by igor-ramazanov** [comment]
@badeball Have you taken a look at `sbtn`?

**Comment by igor-ramazanov** [comment]
@badeball I'd say that the main purpose of `bloop` - is to be leaked.

It's a long-running background process which heavily utilizes incremental compilation and shares the same process across multiple projects - that's what makes it fast.

For CI:
* If it's ok to you to have a long-term running background `bloop` process in the CI, surviving multiple CI builds, then it'll speed up your builds. However, starting from the clean state could be a better idea.
* You can also keep the `bloop` process alive only during the CI session, but then it doesn't differ with having an `sbt` process. E.g. `sbt compile my-project/test` (actually, `sbt my-project/test` most probably depends on the `sbt compile`, so `sbt compile my-project/test` will have almost the same behaviour `sbt my-project/test`). You can spin up a background `sbt` process using `sbtn`.
* With CIs I think it's reasonable to take a look at caching compilation output. There's some progress made by @eed3si9n recently with remote caching.

https://eed3si9n.com/remote-caching-sbt-builds-with-bintray
https://databricks.com/blog/2019/02/27/speedy-scala-builds-with-bazel-at-databricks.html
https://github.com/sbt/sbt/releases/tag/v1.4.0-M1

**Comment by badeball** [comment]
Hey, @igor-ramazanov, thanks for your tips! We've actually just implemented and utilized remote caching and sbtn now and it seems to work great. We're mounting machine-directories into each CI-job, to persist the "remote cache".

My idea / hope with bloop was to kind of have a dedicated & capable machine running that, in which compiling could be offloaded to, while still running tests in container-isolation. But my impression is that that is not possible (yet?).

**Comment by tgodzik** [comment]
Unfortunately, that is not possible yet, but we had some ideas about it and we mostly lack the time currently.

**Pull request merged**
