### PR TITLE
Add ArchLinux package generation

### PR DESCRIPTION
**Pull request by TheElectronWill**
This PR adds two sbt tasks:
- `createLocalArchPackage`, which generates the package files locally
-  `updateArchPackage`, which updates the [AUR bloop package](https://aur.archlinux.org/packages/bloop/). Git authentication is done with an SSH key stored in a file. The file's path is set by the env variable `BLOOPOID_AUR_KEY_PATH`.

One last step to make this work: create a Bloopoid/ScalaCenter AUR account, and I'll make it a maintainer of the bloop package.

_Ping @jvican who I've discussed with about this._

### CODE REVIEW

**Comment by TheElectronWill** [comment]
The private key file contains the basic output of `ssh-keygen` in the following format:
```
-----BEGIN RSA PRIVATE KEY-----
Base64 encoded key data...
-----END RSA PRIVATE KEY-----
```

Your existing keypair can be reused, no problem. I cannot add keys to the repository though, I can only add users. Therefore we'll need to create an account for the ScalaCenter and give it the public key.

**Comment by jvican** [comment]
Perfect, will let you know the signature as the release date for 1.3.0 approaches.

**Comment by jvican** [comment]
@TheElectronWill I've just fixed a few conflicts with the pull request and terminated of integrating your infrastructure with our release pipeline. Again, thanks for this great contribution 🙏 
  
Could you add my AUR username to the bloop git AUR repo? https://aur.archlinux.org/account/jvican You probably don't need the public ssh key but here it is:
  
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqEFhRxJNAFa6Bd8kY3JlwKKVZYclqh9b5XTyd0/3D9O+xt5XSaZ8a7UJj8M3dJ+7xpoo8Y9btV47gsI0Sc+3s0tSIhyWjUfNZeR+/BB+84fawoXbxQo3/IzK565yGp2idppWqpi71/5Bxy2py1wxlVWtRyD2bLlDzJ/CtKZRgHWgl4MlyD/6ffwkiqFdPaF9yrEtoi2OdsxBv/6U60fvQxuGo0LtL3wQy+sIUBCksFZHIhC6Pdv/c592y//Vgjqmujk4dwNnD9uMozEzmRVnfcvVh9RpcrlrIxv3JdSHEsoGZAUD0HL8ZoNKfp8XCPWVuY55tnKZ60cKbb/n8Tfswg+3coRaziCBdwPj+FPCoTKfXOZEPPwkBaqFwW3tJ3gvThO+u+CTYB8s2R3ZZVSEzx5twjiPC8E8+PDplhds+UWPphZyD5EieN7NGBAY6/SxFY8u+qPiUmTmE7pIy0NoQ+PXb+8XULzciU/pz7LFKTyLdNr1IUDtuPncl2dkOduJmtCH6ns2pRLJOCUCEsfboQLUFKom+XcnczuZ4zIfgohoeJlfmoYoRWoSLaidtr1A7SDisX6hbmXwXNvSwhah2V/FHvQvcCOXPG8W4jazX5aKHez2fOwWQyLOfLt73HPTBrVhODAVYG/UiXAkPIG2Oju8iQBpmRM2oM6eoWYLG1Q== jorgevc@fastmail.es
```

**Comment by TheElectronWill** [comment]
Great! I've made your account a maintainer of the AUR package.

**Comment by bloopoid** [comment]
@jvican is about to merge this! @TheElectronWill Could you add me to the co-maintainer list too? I promise to release new bloop versions automatically and timely 😺 My account is https://aur.archlinux.org/account/bloopoid/

**Comment by TheElectronWill** [comment]
Added 😺

**Comment by jvican** [comment]
Awesome work @TheElectronWill

**Pull request merged**
