### PR TITLE
Add release notes for 1.4.6

### PR DESCRIPTION
**Pull request by Duhemm**

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
LGTM!

**Comment by Duhemm** [comment]
All the failures are caused by the Hydra license that is about to expire. I'll move forward with the release and look into this later.

**Comment by tgodzik** [comment]
@TheElectronWill are you able to update the arch package for 1.4.6? I wonder if it's possible to get that step back into the CI in order not to bother you every time? Any idea why it's not there?

**Comment by TheElectronWill** [comment]
> @TheElectronWill are you able to update the arch package for 1.4.6? I wonder if it's possible to get that step back into the CI in order not to bother you every time? Any idea why it's not there?

I've just updated the package. If you have the credentials of the [bloopoid AUR account](https://aur.archlinux.org/account/bloopoid) it should be easy to re-enable the CI. Has Jorge shared them with you? TBH I don't remember well why the AUR publication was disabled at some point.

**Comment by tgodzik** [comment]
Thanks! I don't have those credentials unfortunately. I will try to get them.

**Comment by tgodzik** [comment]
@jvican Do you remember why publishing to AUR was disabled? Also, would be possible to store the credentials somewhere for Scala Center to use?

**Pull request merged**
