### PR TITLE
Prepare for 1.2.5 release

### PR DESCRIPTION
**Pull request by jvican**

### CODE REVIEW

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.oAbGSy8262/2019-02-14-111011-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.aGHu2Aayo3/2019-02-14-111503-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.tkpAms1u1r/2019-02-14-131957-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance plase

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.WH9sZSGeTl/2019-02-14-132405-benchmarks-log.txt for more information]

**Pull request merged**
