### PR TITLE
Fix uploading of benchmarks results

### PR DESCRIPTION
**Pull request by Duhemm**

### CODE REVIEW

**Comment by Duhemm** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by Duhemm** [comment]
The results are correctly being uploaded now

**Comment by jvican** [comment]
Can we run benchmarks on Monix again? @Duhemm I'd like to merge that PR as soon as possible.

**Comment by Duhemm** [comment]
Me too! I'll start them as soon as this PR gets merged.

**Comment by Duhemm** [comment]
Looks like there's still something else that's wrong with the benchmarks. We wait to read "\n> " to know that bloop has finished with the previous command, but somehow we never get that. It used to work fine... I'll look into that now.

**Comment by Duhemm** [comment]
My previous comment is wrong, that's not what's happening. We were no longer running the scripted tests. I've fixed that and added a comment to make sure this won't happen again. That's a good opportunity to check that the benchmarks queue works 😄

**Comment by Duhemm** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 1 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by Duhemm** [comment]
Okay, there was indeed a problem with the benchmarks being stuff since we moved the `loading xxx projects from ...` from info to debug level. I've added a warning about Bloop shell not being the right way to use bloop to fix that.

**Comment by Duhemm** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Pull request merged**
