### PR TITLE
Revert "fix: erase scrollback when clearing the screen"

### PR DESCRIPTION
**Pull request by s-nel**
Reverts scalacenter/bloop#2267 which clears backscroll of the console when in `--watch` mode.

Fixes: #2348

### CODE REVIEW

**Comment by tgodzik** [comment]
@kpodsiad what do you think?

**Comment by kpodsiad** [comment]
Fixing one's workflow breaks another one - https://xkcd.com/1172/ 

Scroll was being cleared previously, but it was cleared improperly. So I think by design and by default watch mode should clear the scroll. 

However, I understand @s-nel preference to not clear it. I wonder, maybe this can be an additional flag? What do you guys think about that?

**Comment by tgodzik** [comment]
> However, I understand @s-nel preference to not clear it. I wonder, maybe this can be an additional flag? What do you guys think about that?

I think flag is the only option to have both cases satisfied

**Comment by s-nel** [comment]
> Scroll was being cleared previously, but it was cleared improperly

It wasn't clearing scroll for me previously. When I start a watch command the console adds a bunch of space so that new lines appear at the top of the console, but everything that ran before is still present in the scrollback. E.g. below I have one `--watch` running, I cancel it, then I start a new `--watch`. The new watch starts at the top of the console but it hasn't cleared anything in the scroll.

```
===============================================
Total duration: 14s
All 1 test suites passed.
===============================================
Watching 50 directories... (press Ctrl-C to interrupt)
^C
$ bloop test ... --watch






























^C
$
```

In any case, I would be happy with a flag

**Pull request closed without merging**
