### PR TITLE
Improve docs and landing page

### PR DESCRIPTION
**Pull request by jvican**
I have seen a lot of misunderstandings with Bloop, how it's installed,
how to set it up, how it works, etc that I've tried to address some of
these misunderstanding by improving the docs: the landing page, the
installation page, and better build tool docs.

The following changes are heavily inspired by the Bazel, Metals and
Babel website, so kudos to all the people that contributed there, they've
been a really important source of inspiration.

Fixes https://github.com/scalacenter/bloop/issues/1180
Fixes https://github.com/scalacenter/bloop/issues/1163

### CODE REVIEW

**Comment by jvican** [comment]
Here are some pictures that show the state of the website after all of these changes.

Screen Shot 2020-03-22 at 23 37 24
Screen Shot 2020-03-22 at 23 37 29
Screen Shot 2020-03-22 at 23 37 39
Screen Shot 2020-03-22 at 23 37 52

**Comment by jvican** [comment]
I'm going to merge, the docs will still be evolving over the next days :smile: I'll submit PRs to fix any bugs I find or style issues. Feedback is welcome.

**Comment by gregestren** [comment]
The Bazel devs really appreciate your inspiration (+https://github.com/jin). The site looks great!

**Comment by jvican** [comment]
Thank you @gregestren, really appreciated!

**Pull request merged**
