### PR TITLE
Filter logs via debug option

### PR DESCRIPTION
**Pull request by ioleo**
The first version to present the idea for solution.

### CODE REVIEW

**Comment by ioleo** [comment]
Related #333

**Comment by ioleo** [comment]
The windows builds are broken / not related to this PR.

**Comment by tues** [comment]
I have some ideas how this could be improved - will try to list them and do a proper review when I get off the train tonight (for now I gave @ioleo some hints).

**Comment by tues** [comment]
Thanks @ioleo, let me know if you need any help with finishing this :slightly_smiling_face:

**Pull request closed without merging**
