### PR TITLE
chore: Unignore Hydra tests

### PR DESCRIPTION
**Pull request by tgodzik**

### CODE REVIEW

**Comment by tgodzik** [comment]
Damn, it's still `Hydra license is missing `

**Comment by ckipp01** [comment]
> Well, this doesn't seem to work anymore :/

I did speak with @dotta about this a bit at the tooling summit and while it's a nice to have, it's not a deal breaker if we can't get it to work.

**Comment by kpodsiad** [comment]
Is someone actually using Bloop + Hydra? Can this be somehow confirmed?

**Comment by tgodzik** [comment]
> Is someone actually using Bloop + Hydra? Can this be somehow confirmed?

Unfortunately it can't :/

**Pull request closed without merging**
