### PR TITLE
chore: Update scala-debug-adapter to newest

### PR DESCRIPTION
**Pull request by tgodzik**

### CODE REVIEW

**Comment by crt-31** [comment]
@tgodzic, or anyone: I'm curious, why wasn't the new scala-debug-adapter detected and updated by the scala-steward? Previous versions have been but this one wasn't.

**Comment by tgodzik** [comment]
I was faster than the steward :D

**Comment by crt-31** [comment]
Sure, but isn't the stewed supposed to run every day?

**Comment by tgodzik** [comment]
> Sure, but isn't the stewed supposed to run every day?

Actually, you are right. https://github.com/scalacenter/steward seems to not be running anymore

**Pull request merged**
