### PR TITLE
Stop shading stuff in sbt-bloop plugins

### PR DESCRIPTION
**Pull request by alexarchambault**
Fixes https://github.com/scalacenter/bloop/issues/1752.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Merging https://github.com/scalacenter/compiler-benchmark/pull/8 is required for the CI here to have a chance to be green.

**Comment by tgodzik** [comment]
> Merging [scalacenter/compiler-benchmark#8](https://github.com/scalacenter/compiler-benchmark/pull/8) is required for the CI here to have a chance to be green (I guess [scalacenter/compiler-benchmark#8](https://github.com/scalacenter/compiler-benchmark/pull/8) can always be reverted by a force push later on if the PR here ends up not being merged.)

Thanks! Done!

**Comment by alexarchambault** [comment]
@tgodzik CI seems to be green. This could be merged if that looks fine to everyone.

**Review by tgodzik — APPROVED** [review]
LGTM! Thanks and sorry I forgot about it!

**Pull request merged**
