### PR TITLE
Update mill docs to point to bloop in mill-contrib

### PR DESCRIPTION
**Pull request by Baccata**
Following https://github.com/lihaoyi/mill/pull/595, this updates the mill-related documentation and tags the implementation as deprecated. 

Alternatively, we could replace the implementation living here by a one liner similar to https://github.com/lihaoyi/mill/pull/595/files#diff-2aa49a8f1843da9f2206f61f9a72c441R10. I'm not sure this would have any benefit in the absence of integration tests. 

- [x] Todo: wait for next mill release (> 0.3.6 ) before merging this

### CODE REVIEW

**Comment by jvican** [comment]
Thanks for this @Baccata Let me know when the new release is out and we'll merge. BTW, if you update this PR, make sure you rebase it :smile:

**Comment by Baccata** [comment]
Forced-push a rebase against master

**Comment by Baccata** [comment]
@jvican mill's latest version was released (it includes the bloop integration) : https://github.com/lihaoyi/mill#038

**Comment by jvican** [comment]
Can we then merge this PR? :smile: @Baccata

**Comment by Baccata** [comment]
> Can we then merge this PR? 

As far as I'm concerned you can, I have no clue what happened to the CI build though :s

**Comment by Baccata** [comment]
@jvican maybe wait, I need to do some testing first 😄

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 1 running.

**Pull request merged**
