### PR TITLE
Add support for BSP TestParamsData kinds

### PR DESCRIPTION
**Pull request by KristianAN**
Adds support for TestParamsData kinds as defined in the scala extension of BSP. This allows clients to specify which test classes / tests to run

Relevant bsp documentation:  https://build-server-protocol.github.io/docs/extensions/scala#testparamsdata-kinds

Fixed a bug? in the TestTask.discoverTestSuites where it did not filter on which test should should
run when explicitly passing list of test classes (fully qualified)

Included tests for running specific test suites, and tests within suites

### CODE REVIEW

**Comment by KristianAN** [comment]
I could not find any tests for test bap service, but maybe I was looking in the wrong place?

**Comment by tgodzik** [comment]
> I could not find any tests for test bsp service, but maybe I was looking in the wrong place?

Did you take a look at `BspTestSpec.scala` ?

**Review by tgodzik — APPROVED** [review]
Looks good! Thanks! Do you want to do anything with this PR or is it good to emrgE?

**Comment by KristianAN** [comment]
It's good to merge as is I think

**Pull request merged**
