### PR TITLE
Control inclusion of javadoc and source artifacts in Gradle

### PR DESCRIPTION
**Pull request by pkolaczk**
This commit allows to
optionally disable downloading javadoc and source artifacts.

In build.gradle:
bloop {
  includeJavadoc = false
  includeSources = false
}

From command line:
gradle bloopInstall -PbloopIncludeJavadoc=false -PbloopIncludeSources=false

### CODE REVIEW

**Comment by pkolaczk** [comment]
Implements #1092

**Comment by jvican** [comment]
@pkolaczk this change doesn’t follow the formatting standards we use in the codebase, please reformat with scalamft and push again, and then we’ll merge.

**Comment by jvican** [comment]
I've actually done this myself, will be merging this when CI is green

**Comment by jvican** [comment]
Actually, no, it doesn't look like I can push to datastax/bloop. This is weird, maybe you checked off the permission to allow me to push? If so, please don't do so when making PRs to this repo. I'll wait on you to push the reformatted changes.

**Comment by jvican** [comment]
Let's reopen this when you have some cycles @pkolaczk

**Pull request closed without merging**
