### PR TITLE
Sbt: Export custom configurations

### LINKED ISSUE #505: Export custom sbt configurations (e.g. IntegrationTest)
Currently the sbt plugin exports only `Main` (e.g. `root`) and `Test` (e.g. `root-test`) configurations. It's quite common for projects to also have `IntegrationTest` configuration: https://www.scala-sbt.org/1.x/docs/Testing.html#Integration+Tests

It would be nice to support at least common configurations like `IntegrationTest`. Exporting all custom configurations would be even better, but obviously Bloop is not a build tool so it's unlikely it would support all weird configurations people may come up with.

Being able to enable/disable export of these additional configurations would probably be a desirable feature for people who don't want to clutter their project namespace.

### PR DESCRIPTION
**Pull request by tues**
To make use of this, one needs to add something along these lines:

```
import bloop.integrations.sbt.BloopDefaults

inConfig(IntegrationTest)(BloopDefaults.configSettings)
```

to project-local settings (preferably a .gitignored `local.sbt`).

TODO:

- [x] Inter-project dependencies (e.g. if `IntegrationTest` depends on `Test`)
- [x] Tests
- [ ] Documentation
- [ ] Probably resolve conflicts with https://github.com/scalacenter/bloop/compare/topic/fix-errors
- [x] Fix CI test failures
- [ ] Update https://github.com/scalacenter/bloop/blob/ticket%2F505-sbt-custom-configs/website/content/faq/_index.md#L44 when the commit ID is known (or change it to `master`?)

Closes #505.

### CODE REVIEW

**Comment by tues** [comment]
The test failure is my fault, I'll fix that.

**Comment by tues** [comment]
I feel I'm stuck, so I have committed my work-in-progress changes adding `bloopDependencies` setting to work around sbt's limitations. It seems to be working well, but I don't like this. I should probably merge `nameFromRef` and `nameFromDependency` into one function, but I'm not sure what `sbt.Classpaths.mapped` is meant to do and the whole `ClasspathDep` vs `ClasspathDependency` and `ProjectRef` vs `ProjectReference` thing is confusing, to say the least.

This could be merged without the last commit (the one marked as `WIP`) and it would still be quite useful, the only disadvantage being the necessity of setting `dependencies` manually in JSON configs for custom configurations (at least if they depend on `compile` or `test`).

Example usage can be found in:
https://github.com/tues/bloop/blob/8516140b246d4c802d476da9f91f4b8aa842e57a/integrations/sbt-bloop/src/sbt-test/sbt-bloop/custom-configurations/build.sbt

**Comment by jvican** [comment]
> I feel I'm stuck, so I have committed my work-in-progress changes adding bloopDependencies setting to work around sbt's limitations. It seems to be working well, but I don't like this. I should probably merge nameFromRef and nameFromDependency into one function, but I'm not sure what sbt.Classpaths.mapped is meant to do and the whole ClasspathDep vs ClasspathDependency and ProjectRef vs ProjectReference thing is confusing, to say the least.
  
Oh yeah, this part of sbt is particularly confusing and magic. It takes a lot of reading to fully understand how it works.
  
I added a commit that solves the problems with configurations automatically so that the user doesn't need to do anything. The key realization in my solution is that dependencies between configurations do not appear in normal classpath deps, but are embedded in the configurations themselves.
  
I've added some code that detects the dependent configurations from which we have to derive inter-project dependencies. These configurations are filtered out so that only the configurations that will generate a bloop configuration file are used.
  
> BTW, the second commit (Rename PluginImplementation to BloopDefaults) is best viewed with white-space changes hidden.
  
Yup, it's not a scary change when you see it only adds 42 lines :smile:
  
I'll be merging this as soon as CI passes since it already gives value. Do you think you can submit another PR adding information to the docs on how to generate configuration files for integrations? I was thinking it may be better to have a new docs page called "Advanced sbt configuration" or something similar in which we put nitty-gritty details on how to do things that are out of scope for the basic installation process.
  
An appereance in the FAQ would also be helpful, redirecting to the advanced sbt configuration page.

**Comment by jvican** [comment]
I'm running the community build to make sure that the generation of bloop config files works for all the projects. In the last commit, I added a test case for #429 which you accidentally fixed by using the well-chosen `inTasks(bloopGenerate)` scope filter :wink:

**Comment by tues** [comment]
Sure, I'll open another PR for the docs later :slightly_smiling_face:

I'm not sure about `config.extendsConfigs` because that was my first approach and it didn't work for the project on which I tested these changes, but maybe there was some other issue involved. We'll see, but I'm sure this is already very useful at least for the majority of sbt projects using custom configs :slightly_smiling_face:

**Comment by jvican** [comment]
> I'm not sure about config.extendsConfigs because that was my first approach and it didn't work for the project on which I tested these changes, but maybe there was some other issue involved. We'll see, but I'm sure this is already very useful at least for the majority of sbt projects using custom configs
  
If it doesn't work for your project, then the issue may be that you're adding a custom classpath dependency that we don't detect in `nameFromDependency`, concretely in the `mapping`. Adding `it` there in the `masterConfs` parameters should work.

**Pull request merged**
