### PR TITLE
Fix testing issues on JDK 11

### PR DESCRIPTION
**Pull request by jvican**

### CODE REVIEW

**Comment by jvican** [comment]
Fixes https://github.com/scalacenter/bloop/issues/588
Fixes https://github.com/scalacenter/bloop/issues/947

**Comment by mushtaq** [comment]
@jvican We also need this for our projects. Should we expect a release soon?

**Comment by jvican** [comment]
@mushtaq Yup

**Comment by mushtaq** [comment]
@jvican awesome, thanks. You know the IntelliJ blog just came out which made me try this and then I hit this one 😄

**Pull request merged**
