### PR TITLE
Update zinc fork with the newest fixes

### PR DESCRIPTION
**Pull request by tgodzik**
Fixes https://github.com/scalacenter/bloop/issues/1598

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
If there was every another sign that we should get off our zinc fork 😅 .

If this indeed fixes the issues then LGTM. Looking at the linked Scala pr to be honest I don't fully comprehend the full ramifications of all the changes in there, so for me this is sort of a "if it's ✅ merge it".

**Comment by tgodzik** [comment]
> If there was every another sign that we should get off our zinc fork sweat_smile .
> 

100% agree

**Comment by ckipp01** [comment]
Great job getting this done btw 🚀 .

**Comment by adpi2** [comment]
Great job @tgodzik and thanks for taking care of it.

**Comment by SethTisue** [comment]
> Looking at the linked Scala pr

What PR is that? (I'm not seeing a link)

**Comment by ckipp01** [comment]
> What PR is that? (I'm not seeing a link)

It was in the linked issue: https://github.com/scala/scala/commit/f51e204fb53f4155320bb5f75271991417453d76

**Comment by SethTisue** [comment]
ah okay, https://github.com/scala/scala/pull/9557

**Comment by SethTisue** [comment]
which is a 2.12.14 PR, I'm a bit curious why this problem didn't manifest earlier, like after the 2.12.14 or 2.12.15 releases? only curious

**Comment by tgodzik** [comment]
> which is a 2.12.14 PR, I'm a bit curious why this problem didn't manifest earlier, like after the 2.12.14 or 2.12.15 releases? only curious

That class is in a 2.13.x specific directory: https://github.com/scalacenter/zinc/tree/main/internal/compiler-bridge/src/main

**Pull request merged**
