### PR TITLE
Update website to integrate Olaf's suggestions

### PR DESCRIPTION
**Pull request by Duhemm**

### CODE REVIEW

**Comment by jvican** [comment]
I ran this on my computer, I liked it. This only changes the button to show the "Getting started" in the frontpage, right? I added a modification to the titles of the getting started guides.

**Comment by Duhemm** [comment]
It also adds the footer in the docs, and adds the "view on GitHub" button on the top right.

**Comment by jvican** [comment]
It seems the footer is not added to the docs, though, only the frontpage. If I go to the installation page, there's no space at the bottom to "breathe". Are you intending to fix that in this PR? :smile:.

**Comment by Duhemm** [comment]
Have you checked out the changes in `kube`?

**Comment by jvican** [comment]
Yes, I have, great work @Duhemm :rocket:

**Pull request merged**
