### PR TITLE
Converting camel case to kebab case configuration flags under autocomplete

### PR DESCRIPTION
**Pull request by rberenguel**
Note: all the tests running `checkInvalidAddress` in `Validate.scala` are failing for me locally (even in a clean pull with no changes done). Not sure why it could be.

I got Case.scala from @olafurpg metaconfig, thanks, it's way neater than what I would have written.

### CODE REVIEW

**Comment by rberenguel** [comment]
I think something on my fork is wrong (I'd blame the submodules, but can't see why), re-forking (also, the approach I took here won't work if autocompletions are autogenerated anyway)

**Comment by jvican** [comment]
Yes, looks like the submodules are off. Did you do `git submodule update --init` right after the clone? That should make things work :wink:

**Comment by rberenguel** [comment]
I knew I was forgetting something, thanks! Not very used to submodules. Will do for the next one, I'm trying another approach to avoid messing with zsh and bash separately in a new fork now :+1:

**Comment by jvican** [comment]
Great, keep in mind that you can also use `hub` which wraps `git` to make sure all submodules are initialized when cloning, it's quite useful just in case you forget to do it yourself :smile:

**Pull request closed without merging**
