### PR TITLE
Disambiguate Gradle project names with project paths

### PR DESCRIPTION
**Pull request by dsilvasc**
…projects with the same name.

### CODE REVIEW

**Comment by dsilvasc** [comment]
We could do that, but it might result in odd or inconsistent names.  For example, suppose you have `:foo-service:client`, `:foo-service:server`, `:bar-service:server`, and `:bar-service:storage`.  You'd have `foo-service-server` and `bar-service-server` in bloop.  But you would also end up with `client` and `storage` in bloop and would have to remember that service foo has a client and service bar has a storage layer -- kind of confusing.  Then when you write a client for service bar, `client` in bloop becomes `foo-service-client`.

**Comment by dsilvasc** [comment]
Yeah that seems reasonable.  I'll change it.

**Comment by jvican** [comment]
Hey @dsilvasc, will you be coming back to this one? I would like to merge it soon so that we wrap up all the good work around the gradle plugin and we release it in a stable version.

**Pull request closed without merging**
