### PR TITLE
Compiling Launcher for 2.13

### LINKED ISSUE #1295: Publish Bloop launcher for Scala 2.13
Currently, the Bloop launcher is only available for Scala 2.12. It would be nice if the launcher was also available for 2.13 so that downstream applications like Metals can upgrade to 2.13 even if the Bloop server runs on 2.12.

### PR DESCRIPTION
**Pull request by keynmol**
~Closes #1295~  It doesn't close anything as it doesn't work yet :D

Given that snailgun with my changes was published for 2.13, I can continue shaving the frontend yak.

The main issue is the need to make a big jump with regards to case-app - a lot has changed, and bloop has huge CLI.

At the moment I'm stuck at not knowing what CommandsMessages is at all, and how it translates to the newer version of case-app

### CODE REVIEW

**Comment by tgodzik** [comment]
@keynmol case app is updated, I think we can work further on this. Do you want to continue or should I take over?

**Comment by keynmol** [comment]
I want to come back to this @tgodzik, yep

Last I worked on bloop codebase I couldn't test anything locally, will resolve this branch and check again.

**Comment by tgodzik** [comment]
> I want to come back to this @tgodzik, yep
> 
> Last I worked on bloop codebase I couldn't test anything locally, will resolve this branch and check again.

Cool! Just ping me about any problems, also discord/gitter. Since most other efforts around Scala 3 have died down, I can concentrate on Bloop more fully.

**Comment by kpodsiad** [comment]
@keynmol I want to give this PR a try. Do you remember anything tricky in cross-compiling bloop launcher?

**Comment by ckipp01** [comment]
> @keynmol I want to give this PR a try. Do you remember anything tricky in cross-compiling bloop launcher?

Not @keynmol, but this was actually the reason why https://github.com/scalacenter/bloop/pull/1544 was all started. I originally thought cross compiling would be a somewhat of simple task but the current dependency graph means that other modules also need to be cross published, and those modules include Monix. That's sort of the issue, the current monix we use isn't available for 2.13.

**Comment by kpodsiad** [comment]
@ckipp01 what's the easiest way to plot only modules graph? https://github.com/sbt/sbt-dependency-graph is plotting graph but it's per module with a lot of noise dependencies.

**Comment by kpodsiad** [comment]
What about rewriting the launcher in Java? It is doable?

**Comment by ckipp01** [comment]
> @ckipp01 what's the easiest way to plot only modules graph? https://github.com/sbt/sbt-dependency-graph is plotting graph but it's per module with a lot of noise dependencies.

Haha ironically you can use Bloop.

`bloop projects --dot-graph | dot -Tsvg -o bloop.svg` or you can also use https://github.com/dwijnand/sbt-project-graph. It looks like this:

projects-graph

> What about rewriting the launcher in Java? It is doable?

Tbh I'm not really sure without looking deeper into it. Maybe.

**Comment by kpodsiad** [comment]
Ok, my SVG differs from yours and the most significant change is that `launcher` doesn't depend on `frontend`.  
I looked for `launcher` in `build.sbt` and I discover that it `dependsOn(sockets, bloopgun, frontend % "test->test")`. `sockets` is a java module, dependency on the frontend is only related to the tests modules. So it leaves only the bloopgun dependecy.

Quick glance at the `bloopgun` deps and it could be easily cross compiled to the 2.13 since all deps are available for 2.13
```shell
ch.epfl.scala:bloopgun-core_2.12:1.4.14 [S]
  +-com.github.plokhotnyuk.jsoniter-scala:jsoniter-scala-core_2.12:2.4.0 [S]
  +-io.get-coursier:interface-svm-subs:1.0.4
  | +-io.get-coursier:interface:1.0.4
  | 
  +-io.get-coursier:interface:1.0.4
  +-me.vican.jorge:snailgun-cli_2.12:0.4.0 [S]
  | +-com.github.scopt:scopt_2.12:4.0.0-RC2 [S]
  | +-me.vican.jorge:snailgun-core_2.12:0.4.0 [S]
  |   +-net.java.dev.jna:jna-platform:5.6.0
  |   | +-net.java.dev.jna:jna:5.6.0
  |   | 
  |   +-net.java.dev.jna:jna:5.6.0
  |   
  +-org.slf4j:slf4j-nop:1.7.2
  | +-org.slf4j:slf4j-api:1.7.2
  | 
  +-org.zeroturnaround:zt-exec:1.11
    +-org.slf4j:slf4j-api:1.7.2
```

I wonder what I'm missing, it seems too easy 🤔 

<details>
  <summary>Btw, here's my graph</summary>
  
bloop

</details>

**Comment by kpodsiad** [comment]
I tried to cross-compile `launcher`, here's [branch](https://github.com/kpodsiad/bloop/commit/e55be17aebfbbb018e1d0a531a83b8c49609ea9a), it's literally 4 loc.

I tried `+launcher/publishLocal` but I was getting errors about frontend not being published for `2.13`, but after I removed `frontend % "test->test"` it works. I didn't get a chance to try it with Metals if it works, but if it'll work I think reorganizing modules to not depend on `frontend % "test->test"` will be tempting.

I also don't know why both launcher and bloopgun are being shaded, can someone explain it to me? (In general, I know what shading is, I just don't get why `launcher` needs to be shaded)

**Comment by ckipp01** [comment]
> I tried +launcher/publishLocal but I was getting errors about frontend not being published for 2.13, but after I removed frontend % "test->test" it works. I didn't get a chance to try it with Metals if it works, but if it'll work I think reorganizing modules to not depend on frontend % "test->test" will be tempting.

😆 I mean if you remove the dep on frontend then yea, it should go smoothly. I mean if they can be split apart, that'd be awesome, but I don't know how easy that would be.

> I also don't know why both launcher and bloopgun are being shaded, can someone explain it to me? (In general, I know what shading is, I just don't get why launcher needs to be shaded)

This one I have no idea about. All the shading in here baffles me. @tgodzik probably knows more.

**Comment by tgodzik** [comment]
Shading is used so that other tools that might want to use Bloop can use them without any issues with dependency versions.

I think that is the main reason

**Comment by kpodsiad** [comment]
> 😆 I mean if you remove the dep on frontend then yea, it should go smoothly. I mean if they can be split apart, that'd be awesome, but I don't know how easy that would be.

`"test->test"` means that the test module depends on the other test module, so there's no runtime dependency between launcher and frontend. That means that it is only a matter of how we structure the tests around the launcher module. That should be relatively easy, but that's bloop we're talking about -- nothing will surprise me 😅

**Comment by tgodzik** [comment]
It's working now in master :tada:

**Pull request closed without merging**
