### PR TITLE
Allow Java versions with a suffix

### PR DESCRIPTION
**Pull request by tgodzik**
Fixes https://github.com/scalacenter/bloop/issues/1656

Checked it locally and this seems to work.

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
Easy fix. LGTM!

**Comment by dos65** [comment]
@tgodzik To be fully safe I think we also need to wrap `toInt` call [here](https://github.com/scalacenter/bloop/blob/21be461a75f9483248d00118cf8c1967e8307e62/frontend/src/main/scala/bloop/data/Project.scala#L195) into `Try`.  Just in case if there will be more unexpected formats of writing version in release file.

**Comment by tgodzik** [comment]
> @tgodzik To be fully safe I think we also need to wrap `toInt` call [here](https://github.com/scalacenter/bloop/blob/21be461a75f9483248d00118cf8c1967e8307e62/frontend/src/main/scala/bloop/data/Project.scala#L195) into `Try`. Just in case if there will be more unexpected formats of writing version in release file.

I wrapped the entire compare into try, should be safe now.

**Review by dos65 — APPROVED** [review]
:+1:

**Comment by tgodzik** [comment]
It seems the debug tests are failing again :/ no change from our side popped up.

**Pull request merged**
