### PR TITLE
Remove obsolete modules

### PR DESCRIPTION
**Pull request by kpodsiad**
As discussed in https://github.com/scalacenter/bloop/discussions/1644

### CODE REVIEW

**Review by tgodzik — CHANGES_REQUESTED** [review]
Could remove any references to `sbtBloop013` ?

We are getting in the CI:
```
Unspecified value parameters sbtBloop013, sbtBloop10.
        .exportCommunityBuild(
```

We could you maybe add somewhere in the docs what version of the sbt plugin needs to be used? It's the version that is used in metals for <=1.3

You should also remove the code that is being used for sbt 0.13

**Comment by kpodsiad** [comment]
Sorry for the notification noise @tgodzik, PR should be created as a draft.

**Comment by kpodsiad** [comment]
@Arthurm1 There are `gradleBloop211` and `gradleBloop212` modules. Does Gradle use both of them or we can safely remove `gradleBloop211`?

**Comment by Arthurm1** [comment]
Sadly it depends on how people are using other Scala plugins.

Gradle plugins share the same classpath.  So if you have no other Gradle plugins _built with Scala_ in your project then it doesn't matter which you add in: `gradleBloop211` or `gradleBloop212`.  But if you do, then you need to add in the one that matches the Scala version of your other plugins.

I've no idea whether anyone is using `211`.  I'd imagine we'd get complaints about Metals if people were as I think Metals adds in `212`.  Although people can use their own init scripts to get round that - maybe some have

Maybe we should remove `211`.  There haven't been any changes to the plugin for a while.  If people have to use `211` then they can use an old version.

**Comment by kpodsiad** [comment]
@tgodzik what do you think?

**Comment by ckipp01** [comment]
> @Arthurm1 There are `gradleBloop211` and `gradleBloop212` modules. Does Gradle use both of them or we can safely remove `gradleBloop211`?

Is it possibly to check the sonatype downloads to see how many there are of the older?

**Comment by tgodzik** [comment]
> gradleBloop211

Let me try to figure it out.

**Comment by ckipp01** [comment]
This was done in https://github.com/scalacenter/bloop/pull/1852 so I'm going to go ahead and close this one.

**Pull request closed without merging**
