### PR TITLE
refactor: Remove custom component manager and compiler

### PR DESCRIPTION
**Pull request by tgodzik**
The only issue here is that it removes support for Hydra, but I don't really want to support it as we can't test it.

I will see if the PR actually works and maybe try to add Hydra in a better way.

Prompted by https://github.com/sbt/zinc/pull/1215#discussion_r1258457060

### CODE REVIEW

**Comment by tgodzik** [comment]
@ckipp01 did you ever get that hydra license from @dotta ?

**Comment by ckipp01** [comment]
> @ckipp01 did you ever get that hydra license from @dotta ?

Yuuup, I have it. I believe I actually added it to the repo secrets so it should be there. DM me tomorrow and I can get it to you.

**Comment by tgodzik** [comment]
> > @ckipp01 did you ever get that hydra license from @dotta ?
> 
> Yuuup, I have it. I believe I actually added it to the repo secrets so it should be there. DM me tomorrow and I can get it to you.

Here is the reason: https://github.com/scalacenter/bloop/pull/2113 :s

**Comment by tgodzik** [comment]
Will leave it as is for now, since it's not super urgent.

**Pull request closed without merging**
