### PR TITLE
Enable old project in benchmarks again

### PR DESCRIPTION
**Pull request by jvican**
The previous projects were not being benchmarked after the experiments with
pipelined compilation. Let's get a solid baseline with these projects and then
improve bloop from there.

### CODE REVIEW

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs</summary>

</details>

Error line number: 121

[check /tmp/tmp.kJbitixdQb/2018-08-07-172923-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 1 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs</summary>

</details>

Error line number: 121

[check /tmp/tmp.ND02ahRuAT/2018-08-08-001259-benchmarks-log.txt for more information]

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs</summary>

</details>

Error line number: 96

[check  for more information]

**Comment by jvican** [comment]
test performance please

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs</summary>

</details>

Error line number: 121

[check /tmp/tmp.OwXOfRR5Bf/2018-08-08-114555-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.mfWteeK4j7/2018-08-08-171537-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.hyKQtyZbfg/2018-08-08-172954-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.f7ygVnF8xA/2018-08-08-173711-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test failed:

<details>
  <summary>Benchmark logs (last 200 lines)</summary>

</details>

Error line number: 122

[check /tmp/tmp.w2Q7mbwHpM/2018-08-08-174027-benchmarks-log.txt for more information]

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 0 running.

**Comment by jvican** [comment]
test performance please

**Comment by bloopoid** [comment]
performance test scheduled: 1 job(s) in queue, 1 running.

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Comment by bloopoid** [comment]
Performance test finished successfully.

Benchmarks is based on merging with master

**Pull request merged**
