### PR TITLE
bugfix: Try and fix issue with Base64 reflection

### PR DESCRIPTION
**Pull request by tgodzik**
Based on https://github.com/dirs-dev/directories-jvm/blob/aa87fc1705fec69bc7f486dae6910306a50c221a/src/main/resources/META-INF/native-image/dev.dirs/reflect-config.json

Fixes https://github.com/scalacenter/bloop/issues/1718

### CODE REVIEW

**Comment by tgodzik** [comment]
Anyone willing to test it out on windows? Otherwise I can do that probably next week and run a new release.

**Comment by tgodzik** [comment]
I tried releasing it locally on Windows, but it seems a bottomless rabbit hole :/

Try is a simple instruction:
`gu.cmd install native-image` which should install `native-image.cmd` in the same folder, but it doesn't! 

Spent an hour trying to google/fix that, but to no avail. I found `native-image.exe`, is that the same thing? It's in a totally different folder, but maybe it does work?

Then it started failing with not finding cl.exe, which needed Visual Studio being installed (!!!) and it still didn't help.

I think we will check this when the release runs :/

**Comment by ckipp01** [comment]
I honestly know nothing about what this is doing. Do you have any links or reference to what these are?

**Comment by tgodzik** [comment]
There is a bit more here: https://www.graalvm.org/22.1/reference-manual/native-image/Reflection/

But I ma kind of guessing here and copying from dev-dirs, which seems to have that setting

**Review by adpi2 — APPROVED** [review]
Ok, so this dirs-dev library tries to load `java.util.Base64` 
by reflection [here](https://github.com/dirs-dev/directories-jvm/blob/aa87fc1705fec69bc7f486dae6910306a50c221a/src/main/java/dev/dirs/Util.java#L185-L197) and to call `getEncoder` which probably returns a `java.util.Base64$Encoder`.

I wonder if we should also declare `sun.misc.BASE64Encoder` here. Probably not if we compile with Java 11 or greater.

I cannot test this change now but it seems perfectly legitimate to me.

**Comment by tgodzik** [comment]
> Ok, so this dirs-dev library tries to load `java.util.Base64` by reflection [here](https://github.com/dirs-dev/directories-jvm/blob/aa87fc1705fec69bc7f486dae6910306a50c221a/src/main/java/dev/dirs/Util.java#L185-L197) and to call `getEncoder` which probably returns a `java.util.Base64$Encoder`.
> 
> I wonder if we should also declare `sun.misc.BASE64Encoder` here. Probably not if we compile with Java 11 or greater.
> 
> I cannot test this change now but it seems perfectly legitimate to me.

I will try and build it on CI, might be possible to download it and test on windows.

**Comment by tgodzik** [comment]
> I will try and build it on CI, might be possible to download it and test on windows.

That actually worked! :tada:

**Review by ckipp01 — APPROVED** [review]
Alrighty, finally read through the link. Thanks! From what I can tell, yea this makes sense. LGTM

**Pull request merged**
